<a href="https://colab.research.google.com/github/ggsgranados/Pandas_I-O/blob/main/SQL_con_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Leyendo banco de datos

## Creando un banco de datos local

In [1]:
# ORM a utilizar
import sqlalchemy

In [2]:
# Importaciones:
# create_engine genera el entorno de la base de datos
# MetaData guarda la informacion
# Table para poder trabajar con ellas
# inspect para inspeccionar bancos de datos
# text para convertir las querys en texto
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [3]:
# Usando la memoria local de Collab
engine = create_engine('sqlite:///:memory:')

## Escribiendo en un banco de datos

In [4]:
import pandas as pd

In [5]:
archivo = '/content/clientes_banco.csv'

In [6]:
# Colocando el csv en un dataframe para poder ingresarlo en la base de datos
datos = pd.read_csv(archivo)

In [7]:
datos.head(4)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [8]:
# Parámetros
# (nombre, motor, quitando_indices)
datos.to_sql('clientes', engine, index=False)

438463

In [9]:
# Revisando lo que hay en el motor y asignandolo en una variable
inspector = inspect(engine)

In [10]:
print(inspector.get_table_names())

['clientes']

## Leyendo una consulta SQL

In [11]:
# Almacenando la query
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [12]:
# Forma 01 de realizar la query
empleados = pd.read_sql(sql=text(query), con=engine.connect())

In [13]:
# Forma 02 de realizar la query
empleados2 = pd.read_sql(query, engine)

In [14]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [15]:
type(empleados)

pandas.core.frame.DataFrame

In [16]:
# Guardando la nueva tabla
empleados.to_sql('empleados', con=engine.connect(), index=False)

226059

In [17]:
pd.read_sql_table('empleados', engine)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [18]:
# Filtrando resultados
pd.read_sql_table('empleados', engine, columns=['ID_Cliente', 'Grado_estudio','Rendimiento_anual'])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

## Actualizando un banco de datos

In [19]:
query = 'Select * from clientes'

In [20]:
pd.read_sql(sql=text(query), con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [21]:
# Borrando registros
# Manejo de errores
from sqlalchemy.exc import SQLAlchemyError

query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('#Registros borrados', r_set.rowcount)

#Registros borrados 1

In [22]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [23]:
# Actualizando registros
# Manejo de errores

query = 'UPDATE clientes SET Grado_estudio = "Nivel superior" WHERE ID_Cliente = 5008808'
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('#Registros actualizados', r_set.rowcount)

#Registros actualizados 1

In [24]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [25]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']